require: rubocop-rails

Rails:
  Enabled: true
AllCops:
  Exclude:
    - "bin/*"
    - "bundle_cache/**/*"
    - "config/**/*"
    - "db/**/*"
    - "node_modules/**/*"
    - "script/**/*"
    - "tmp/**/*"
    - "vendor/**/*"

Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Max: 114
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/LineLength:
  Max: 125
Metrics/MethodLength:
  Max: 30
Metrics/ModuleLength:
  Max: 145
Metrics/PerceivedComplexity:
  Max: 10

Style/AsciiComments:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/NumericPredicate:
  Exclude:
    - "spec/**/*"

Style/FrozenStringLiteralComment:
  Enabled: false
