version: '3'

services:
  db:
    image: postgres:10.6
    container_name: courses_db
  web:
    build: .
    image: courses/web:latest
    container_name: courses-web
    command: bash -c "puma"
    ports:
      - 8080:8080
    volumes:
      - ./:/app